all_data<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings ="?")
desired_data<-subset(all_data,Date %in% c("1/2/2007","2/2/2007"))
desired_data$Date<-as.Date(desired_data$Date,"%d/%m/%Y")  
time<-paste(as.Date(desired_data$Date),desired_data$Time)
desired_data$time <- as.POSIXct(time)

# plot 4 and save to png
#png("plot4.png", width=480, height=480)
par(mfrow=c(2,2),mar=c(4,4,2,1))
with(desired_data,plot(Global_active_power~time,type="l",xlab="",ylab="Global Active Power (kilowatts)"))
with(desired_data,plot(Voltage~time,type="l",xlab="datetime"))
with(desired_data,{plot(Sub_metering_1~time,type="l",xlab="",ylab="Energy sub metering")
  lines(Sub_metering_2~time,col="red")
  lines(Sub_metering_3~time,col="blue")
legend("topright", col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1,lwd=2,cex=0.5)
})
with(desired_data,plot(Global_reactive_power~time,type="l",xlab="datetime"))
dev.copy(png,file="plot4.png", height=480, width=480)
dev.off()
